Firestore typescript migration
wix/velo-external-db pull request #336
Opened 2022-07-19 13:19 UTC by MXPOL

2022-07-19 14:08 UTC, Idokah requested changes

2022-07-20 11:54 UTC, MXPOL commented on libs/external-db-firestore/src/firestore_utils.ts
> +export const asEntity = (docEntity: any) => {
nope, its not an Item object, as you can see in line 14 I'm using a method inside this object...

2022-07-27 11:55 UTC, Idokah commented on libs/external-db-firestore/src/firestore_schema_provider.ts
> +    reformatFields(field: { name: any; type: any }) {
`field: InputField`
or at least name: string, type: string

2022-07-27 11:59 UTC, Idokah approved these changes

2022-07-27 12:05 UTC, merged